# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/YSFlight/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/YSFlight

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/YSFlight/CMakeFiles /tmp/YSFlight//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/YSFlight/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ysclass

# Build rule for target.
ysclass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysclass
.PHONY : ysclass

# fast build rule for target.
ysclass/fast:
	$(MAKE) $(MAKESILENT) -f public/ysclass/src/CMakeFiles/ysclass.dir/build.make public/ysclass/src/CMakeFiles/ysclass.dir/build
.PHONY : ysclass/fast

#=============================================================================
# Target rules for targets named ysclass11

# Build rule for target.
ysclass11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysclass11
.PHONY : ysclass11

# fast build rule for target.
ysclass11/fast:
	$(MAKE) $(MAKESILENT) -f public/ysclass11/src/CMakeFiles/ysclass11.dir/build.make public/ysclass11/src/CMakeFiles/ysclass11.dir/build
.PHONY : ysclass11/fast

#=============================================================================
# Target rules for targets named ysport

# Build rule for target.
ysport: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysport
.PHONY : ysport

# fast build rule for target.
ysport/fast:
	$(MAKE) $(MAKESILENT) -f public/ysport/src/CMakeFiles/ysport.dir/build.make public/ysport/src/CMakeFiles/ysport.dir/build
.PHONY : ysport/fast

#=============================================================================
# Target rules for targets named ysgl_makec

# Build rule for target.
ysgl_makec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysgl_makec
.PHONY : ysgl_makec

# fast build rule for target.
ysgl_makec/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysgl_makec.dir/build.make public/ysgl/src/CMakeFiles/ysgl_makec.dir/build
.PHONY : ysgl_makec/fast

#=============================================================================
# Target rules for targets named ysgl_makeh

# Build rule for target.
ysgl_makeh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysgl_makeh
.PHONY : ysgl_makeh

# fast build rule for target.
ysgl_makeh/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysgl_makeh.dir/build.make public/ysgl/src/CMakeFiles/ysgl_makeh.dir/build
.PHONY : ysgl_makeh/fast

#=============================================================================
# Target rules for targets named ysgl_preproc

# Build rule for target.
ysgl_preproc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysgl_preproc
.PHONY : ysgl_preproc

# fast build rule for target.
ysgl_preproc/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysgl_preproc.dir/build.make public/ysgl/src/CMakeFiles/ysgl_preproc.dir/build
.PHONY : ysgl_preproc/fast

#=============================================================================
# Target rules for targets named ysglsl_expand_source

# Build rule for target.
ysglsl_expand_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglsl_expand_source
.PHONY : ysglsl_expand_source

# fast build rule for target.
ysglsl_expand_source/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysglsl_expand_source.dir/build.make public/ysgl/src/CMakeFiles/ysglsl_expand_source.dir/build
.PHONY : ysglsl_expand_source/fast

#=============================================================================
# Target rules for targets named ysglslprogram_c

# Build rule for target.
ysglslprogram_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglslprogram_c
.PHONY : ysglslprogram_c

# fast build rule for target.
ysglslprogram_c/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysglslprogram_c.dir/build.make public/ysgl/src/CMakeFiles/ysglslprogram_c.dir/build
.PHONY : ysglslprogram_c/fast

#=============================================================================
# Target rules for targets named ysglslprogram_h

# Build rule for target.
ysglslprogram_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglslprogram_h
.PHONY : ysglslprogram_h

# fast build rule for target.
ysglslprogram_h/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysglslprogram_h.dir/build.make public/ysgl/src/CMakeFiles/ysglslprogram_h.dir/build
.PHONY : ysglslprogram_h/fast

#=============================================================================
# Target rules for targets named ysgl

# Build rule for target.
ysgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysgl
.PHONY : ysgl

# fast build rule for target.
ysgl/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgl/src/CMakeFiles/ysgl.dir/build.make public/ysgl/src/CMakeFiles/ysgl.dir/build
.PHONY : ysgl/fast

#=============================================================================
# Target rules for targets named ysglcpp

# Build rule for target.
ysglcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglcpp
.PHONY : ysglcpp

# fast build rule for target.
ysglcpp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysglcpp/src/CMakeFiles/ysglcpp.dir/build.make public/ysglcpp/src/CMakeFiles/ysglcpp.dir/build
.PHONY : ysglcpp/fast

#=============================================================================
# Target rules for targets named ysglcpp_gl2

# Build rule for target.
ysglcpp_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglcpp_gl2
.PHONY : ysglcpp_gl2

# fast build rule for target.
ysglcpp_gl2/fast:
	$(MAKE) $(MAKESILENT) -f public/ysglcpp/src/gl2/CMakeFiles/ysglcpp_gl2.dir/build.make public/ysglcpp/src/gl2/CMakeFiles/ysglcpp_gl2.dir/build
.PHONY : ysglcpp_gl2/fast

#=============================================================================
# Target rules for targets named ysglcpp_gl1

# Build rule for target.
ysglcpp_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglcpp_gl1
.PHONY : ysglcpp_gl1

# fast build rule for target.
ysglcpp_gl1/fast:
	$(MAKE) $(MAKESILENT) -f public/ysglcpp/src/gl1/CMakeFiles/ysglcpp_gl1.dir/build.make public/ysglcpp/src/gl1/CMakeFiles/ysglcpp_gl1.dir/build
.PHONY : ysglcpp_gl1/fast

#=============================================================================
# Target rules for targets named ysglcpp_nownd

# Build rule for target.
ysglcpp_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysglcpp_nownd
.PHONY : ysglcpp_nownd

# fast build rule for target.
ysglcpp_nownd/fast:
	$(MAKE) $(MAKESILENT) -f public/ysglcpp/src/nownd/CMakeFiles/ysglcpp_nownd.dir/build.make public/ysglcpp/src/nownd/CMakeFiles/ysglcpp_nownd.dir/build
.PHONY : ysglcpp_nownd/fast

#=============================================================================
# Target rules for targets named ysbitmap

# Build rule for target.
ysbitmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysbitmap
.PHONY : ysbitmap

# fast build rule for target.
ysbitmap/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/src/CMakeFiles/ysbitmap.dir/build.make public/ysbitmap/src/CMakeFiles/ysbitmap.dir/build
.PHONY : ysbitmap/fast

#=============================================================================
# Target rules for targets named ys_bitmap_command_base

# Build rule for target.
ys_bitmap_command_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ys_bitmap_command_base
.PHONY : ys_bitmap_command_base

# fast build rule for target.
ys_bitmap_command_base/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ys_bitmap_command_base.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ys_bitmap_command_base.dir/build
.PHONY : ys_bitmap_command_base/fast

#=============================================================================
# Target rules for targets named ysmakebmptile

# Build rule for target.
ysmakebmptile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakebmptile
.PHONY : ysmakebmptile

# fast build rule for target.
ysmakebmptile/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakebmptile.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakebmptile.dir/build
.PHONY : ysmakebmptile/fast

#=============================================================================
# Target rules for targets named ysmakeblackwhite

# Build rule for target.
ysmakeblackwhite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakeblackwhite
.PHONY : ysmakeblackwhite

# fast build rule for target.
ysmakeblackwhite/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakeblackwhite.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakeblackwhite.dir/build
.PHONY : ysmakeblackwhite/fast

#=============================================================================
# Target rules for targets named ysresizebmp

# Build rule for target.
ysresizebmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysresizebmp
.PHONY : ysresizebmp

# fast build rule for target.
ysresizebmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysresizebmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysresizebmp.dir/build
.PHONY : ysresizebmp/fast

#=============================================================================
# Target rules for targets named ysmakewhitetransparent

# Build rule for target.
ysmakewhitetransparent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakewhitetransparent
.PHONY : ysmakewhitetransparent

# fast build rule for target.
ysmakewhitetransparent/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakewhitetransparent.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakewhitetransparent.dir/build
.PHONY : ysmakewhitetransparent/fast

#=============================================================================
# Target rules for targets named ysnegatebmp

# Build rule for target.
ysnegatebmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysnegatebmp
.PHONY : ysnegatebmp

# fast build rule for target.
ysnegatebmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysnegatebmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysnegatebmp.dir/build
.PHONY : ysnegatebmp/fast

#=============================================================================
# Target rules for targets named ysmakeblankbmp

# Build rule for target.
ysmakeblankbmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakeblankbmp
.PHONY : ysmakeblankbmp

# fast build rule for target.
ysmakeblankbmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakeblankbmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakeblankbmp.dir/build
.PHONY : ysmakeblankbmp/fast

#=============================================================================
# Target rules for targets named ysinvertbmp

# Build rule for target.
ysinvertbmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysinvertbmp
.PHONY : ysinvertbmp

# fast build rule for target.
ysinvertbmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysinvertbmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysinvertbmp.dir/build
.PHONY : ysinvertbmp/fast

#=============================================================================
# Target rules for targets named ysmakedensitymap

# Build rule for target.
ysmakedensitymap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakedensitymap
.PHONY : ysmakedensitymap

# fast build rule for target.
ysmakedensitymap/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakedensitymap.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakedensitymap.dir/build
.PHONY : ysmakedensitymap/fast

#=============================================================================
# Target rules for targets named ysmakealphamask

# Build rule for target.
ysmakealphamask: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmakealphamask
.PHONY : ysmakealphamask

# fast build rule for target.
ysmakealphamask/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/ysmakealphamask.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/ysmakealphamask.dir/build
.PHONY : ysmakealphamask/fast

#=============================================================================
# Target rules for targets named yspastebmp

# Build rule for target.
yspastebmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yspastebmp
.PHONY : yspastebmp

# fast build rule for target.
yspastebmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/yspastebmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/yspastebmp.dir/build
.PHONY : yspastebmp/fast

#=============================================================================
# Target rules for targets named yscropbmp

# Build rule for target.
yscropbmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yscropbmp
.PHONY : yscropbmp

# fast build rule for target.
yscropbmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmap/cmdtools/CMakeFiles/yscropbmp.dir/build.make public/ysbitmap/cmdtools/CMakeFiles/yscropbmp.dir/build
.PHONY : yscropbmp/fast

#=============================================================================
# Target rules for targets named ysbitmaputil

# Build rule for target.
ysbitmaputil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysbitmaputil
.PHONY : ysbitmaputil

# fast build rule for target.
ysbitmaputil/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmaputil/src/CMakeFiles/ysbitmaputil.dir/build.make public/ysbitmaputil/src/CMakeFiles/ysbitmaputil.dir/build
.PHONY : ysbitmaputil/fast

#=============================================================================
# Target rules for targets named ysbitmapfont

# Build rule for target.
ysbitmapfont: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysbitmapfont
.PHONY : ysbitmapfont

# fast build rule for target.
ysbitmapfont/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmapfont/src/CMakeFiles/ysbitmapfont.dir/build.make public/ysbitmapfont/src/CMakeFiles/ysbitmapfont.dir/build
.PHONY : ysbitmapfont/fast

#=============================================================================
# Target rules for targets named ysmaketextbmp

# Build rule for target.
ysmaketextbmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysmaketextbmp
.PHONY : ysmaketextbmp

# fast build rule for target.
ysmaketextbmp/fast:
	$(MAKE) $(MAKESILENT) -f public/ysbitmapfont/cmdtools/CMakeFiles/ysmaketextbmp.dir/build.make public/ysbitmapfont/cmdtools/CMakeFiles/ysmaketextbmp.dir/build
.PHONY : ysmaketextbmp/fast

#=============================================================================
# Target rules for targets named yssystemfont

# Build rule for target.
yssystemfont: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssystemfont
.PHONY : yssystemfont

# fast build rule for target.
yssystemfont/fast:
	$(MAKE) $(MAKESILENT) -f public/yssystemfont/src/CMakeFiles/yssystemfont.dir/build.make public/yssystemfont/src/CMakeFiles/yssystemfont.dir/build
.PHONY : yssystemfont/fast

#=============================================================================
# Target rules for targets named ysnullsystemfont

# Build rule for target.
ysnullsystemfont: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysnullsystemfont
.PHONY : ysnullsystemfont

# fast build rule for target.
ysnullsystemfont/fast:
	$(MAKE) $(MAKESILENT) -f public/yssystemfont/src/CMakeFiles/ysnullsystemfont.dir/build.make public/yssystemfont/src/CMakeFiles/ysnullsystemfont.dir/build
.PHONY : ysnullsystemfont/fast

#=============================================================================
# Target rules for targets named fssimplewindow

# Build rule for target.
fssimplewindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fssimplewindow
.PHONY : fssimplewindow

# fast build rule for target.
fssimplewindow/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/src/CMakeFiles/fssimplewindow.dir/build.make public/fssimplewindow/src/CMakeFiles/fssimplewindow.dir/build
.PHONY : fssimplewindow/fast

#=============================================================================
# Target rules for targets named fssimplenowindow

# Build rule for target.
fssimplenowindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fssimplenowindow
.PHONY : fssimplenowindow

# fast build rule for target.
fssimplenowindow/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/src/CMakeFiles/fssimplenowindow.dir/build.make public/fssimplewindow/src/CMakeFiles/fssimplenowindow.dir/build
.PHONY : fssimplenowindow/fast

#=============================================================================
# Target rules for targets named test_fullscreen

# Build rule for target.
test_fullscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fullscreen
.PHONY : test_fullscreen

# fast build rule for target.
test_fullscreen/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/src/tests/CMakeFiles/test_fullscreen.dir/build.make public/fssimplewindow/src/tests/CMakeFiles/test_fullscreen.dir/build
.PHONY : test_fullscreen/fast

#=============================================================================
# Target rules for targets named test_resize

# Build rule for target.
test_resize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_resize
.PHONY : test_resize

# fast build rule for target.
test_resize/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/src/tests/CMakeFiles/test_resize.dir/build.make public/fssimplewindow/src/tests/CMakeFiles/test_resize.dir/build
.PHONY : test_resize/fast

#=============================================================================
# Target rules for targets named fssimplewindow_template

# Build rule for target.
fssimplewindow_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fssimplewindow_template
.PHONY : fssimplewindow_template

# fast build rule for target.
fssimplewindow_template/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/template/CMakeFiles/fssimplewindow_template.dir/build.make public/fssimplewindow/template/CMakeFiles/fssimplewindow_template.dir/build
.PHONY : fssimplewindow_template/fast

#=============================================================================
# Target rules for targets named sample00-lineart

# Build rule for target.
sample00-lineart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample00-lineart
.PHONY : sample00-lineart

# fast build rule for target.
sample00-lineart/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample00-lineart.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample00-lineart.dir/build
.PHONY : sample00-lineart/fast

#=============================================================================
# Target rules for targets named sample01-squash

# Build rule for target.
sample01-squash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample01-squash
.PHONY : sample01-squash

# fast build rule for target.
sample01-squash/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample01-squash.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample01-squash.dir/build
.PHONY : sample01-squash/fast

#=============================================================================
# Target rules for targets named sample02-echo

# Build rule for target.
sample02-echo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample02-echo
.PHONY : sample02-echo

# fast build rule for target.
sample02-echo/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample02-echo.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample02-echo.dir/build
.PHONY : sample02-echo/fast

#=============================================================================
# Target rules for targets named sample03-mouse

# Build rule for target.
sample03-mouse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample03-mouse
.PHONY : sample03-mouse

# fast build rule for target.
sample03-mouse/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample03-mouse.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample03-mouse.dir/build
.PHONY : sample03-mouse/fast

#=============================================================================
# Target rules for targets named sample04-cube

# Build rule for target.
sample04-cube: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample04-cube
.PHONY : sample04-cube

# fast build rule for target.
sample04-cube/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample04-cube.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample04-cube.dir/build
.PHONY : sample04-cube/fast

#=============================================================================
# Target rules for targets named sample05-key

# Build rule for target.
sample05-key: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample05-key
.PHONY : sample05-key

# fast build rule for target.
sample05-key/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample05-key.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample05-key.dir/build
.PHONY : sample05-key/fast

#=============================================================================
# Target rules for targets named sample06-15puzzle

# Build rule for target.
sample06-15puzzle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample06-15puzzle
.PHONY : sample06-15puzzle

# fast build rule for target.
sample06-15puzzle/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplewindow/samples/CMakeFiles/sample06-15puzzle.dir/build.make public/fssimplewindow/samples/CMakeFiles/sample06-15puzzle.dir/build
.PHONY : sample06-15puzzle/fast

#=============================================================================
# Target rules for targets named yssimplesound

# Build rule for target.
yssimplesound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound
.PHONY : yssimplesound

# fast build rule for target.
yssimplesound/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/CMakeFiles/yssimplesound.dir/build.make public/yssimplesound/src/CMakeFiles/yssimplesound.dir/build
.PHONY : yssimplesound/fast

#=============================================================================
# Target rules for targets named yssimplesound_nownd

# Build rule for target.
yssimplesound_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_nownd
.PHONY : yssimplesound_nownd

# fast build rule for target.
yssimplesound_nownd/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/CMakeFiles/yssimplesound_nownd.dir/build.make public/yssimplesound/src/CMakeFiles/yssimplesound_nownd.dir/build
.PHONY : yssimplesound_nownd/fast

#=============================================================================
# Target rules for targets named yssimplesound_linux_alsa

# Build rule for target.
yssimplesound_linux_alsa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_linux_alsa
.PHONY : yssimplesound_linux_alsa

# fast build rule for target.
yssimplesound_linux_alsa/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/CMakeFiles/yssimplesound_linux_alsa.dir/build.make public/yssimplesound/src/CMakeFiles/yssimplesound_linux_alsa.dir/build
.PHONY : yssimplesound_linux_alsa/fast

#=============================================================================
# Target rules for targets named yssimplesound_test01

# Build rule for target.
yssimplesound_test01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_test01
.PHONY : yssimplesound_test01

# fast build rule for target.
yssimplesound_test01/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_test01.dir/build.make public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_test01.dir/build
.PHONY : yssimplesound_test01/fast

#=============================================================================
# Target rules for targets named yssimplesound_stressTest

# Build rule for target.
yssimplesound_stressTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_stressTest
.PHONY : yssimplesound_stressTest

# fast build rule for target.
yssimplesound_stressTest/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_stressTest.dir/build.make public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_stressTest.dir/build
.PHONY : yssimplesound_stressTest/fast

#=============================================================================
# Target rules for targets named yssimplesound_streamtest

# Build rule for target.
yssimplesound_streamtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_streamtest
.PHONY : yssimplesound_streamtest

# fast build rule for target.
yssimplesound_streamtest/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_streamtest.dir/build.make public/yssimplesound/src/unittest/CMakeFiles/yssimplesound_streamtest.dir/build
.PHONY : yssimplesound_streamtest/fast

#=============================================================================
# Target rules for targets named playwav

# Build rule for target.
playwav: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 playwav
.PHONY : playwav

# fast build rule for target.
playwav/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/src/playwav/CMakeFiles/playwav.dir/build.make public/yssimplesound/src/playwav/CMakeFiles/playwav.dir/build
.PHONY : playwav/fast

#=============================================================================
# Target rules for targets named yssimplesound_test

# Build rule for target.
yssimplesound_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_test
.PHONY : yssimplesound_test

# fast build rule for target.
yssimplesound_test/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/test/CMakeFiles/yssimplesound_test.dir/build.make public/yssimplesound/test/CMakeFiles/yssimplesound_test.dir/build
.PHONY : yssimplesound_test/fast

#=============================================================================
# Target rules for targets named yssimplesound_sample

# Build rule for target.
yssimplesound_sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_sample
.PHONY : yssimplesound_sample

# fast build rule for target.
yssimplesound_sample/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/sample/CMakeFiles/yssimplesound_sample.dir/build.make public/yssimplesound/sample/CMakeFiles/yssimplesound_sample.dir/build
.PHONY : yssimplesound_sample/fast

#=============================================================================
# Target rules for targets named yssimplesound_sample_fssimplewindow

# Build rule for target.
yssimplesound_sample_fssimplewindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssimplesound_sample_fssimplewindow
.PHONY : yssimplesound_sample_fssimplewindow

# fast build rule for target.
yssimplesound_sample_fssimplewindow/fast:
	$(MAKE) $(MAKESILENT) -f public/yssimplesound/sample_fssimplewindow/CMakeFiles/yssimplesound_sample_fssimplewindow.dir/build.make public/yssimplesound/sample_fssimplewindow/CMakeFiles/yssimplesound_sample_fssimplewindow.dir/build
.PHONY : yssimplesound_sample_fssimplewindow/fast

#=============================================================================
# Target rules for targets named fslazywindow

# Build rule for target.
fslazywindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fslazywindow
.PHONY : fslazywindow

# fast build rule for target.
fslazywindow/fast:
	$(MAKE) $(MAKESILENT) -f public/fslazywindow/src/CMakeFiles/fslazywindow.dir/build.make public/fslazywindow/src/CMakeFiles/fslazywindow.dir/build
.PHONY : fslazywindow/fast

#=============================================================================
# Target rules for targets named fslazywindow_template

# Build rule for target.
fslazywindow_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fslazywindow_template
.PHONY : fslazywindow_template

# fast build rule for target.
fslazywindow_template/fast:
	$(MAKE) $(MAKESILENT) -f public/fslazywindow/template/CMakeFiles/fslazywindow_template.dir/build.make public/fslazywindow/template/CMakeFiles/fslazywindow_template.dir/build
.PHONY : fslazywindow_template/fast

#=============================================================================
# Target rules for targets named sample00_bouncingBall

# Build rule for target.
sample00_bouncingBall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample00_bouncingBall
.PHONY : sample00_bouncingBall

# fast build rule for target.
sample00_bouncingBall/fast:
	$(MAKE) $(MAKESILENT) -f public/fslazywindow/samples/sample00-bouncingBall/CMakeFiles/sample00_bouncingBall.dir/build.make public/fslazywindow/samples/sample00-bouncingBall/CMakeFiles/sample00_bouncingBall.dir/build
.PHONY : sample00_bouncingBall/fast

#=============================================================================
# Target rules for targets named fssimplefiledialog

# Build rule for target.
fssimplefiledialog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fssimplefiledialog
.PHONY : fssimplefiledialog

# fast build rule for target.
fssimplefiledialog/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplefiledialog/src/CMakeFiles/fssimplefiledialog.dir/build.make public/fssimplefiledialog/src/CMakeFiles/fssimplefiledialog.dir/build
.PHONY : fssimplefiledialog/fast

#=============================================================================
# Target rules for targets named fssimplefiledialog_sample

# Build rule for target.
fssimplefiledialog_sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fssimplefiledialog_sample
.PHONY : fssimplefiledialog_sample

# fast build rule for target.
fssimplefiledialog_sample/fast:
	$(MAKE) $(MAKESILENT) -f public/fssimplefiledialog/sample/CMakeFiles/fssimplefiledialog_sample.dir/build.make public/fssimplefiledialog/sample/CMakeFiles/fssimplefiledialog_sample.dir/build
.PHONY : fssimplefiledialog_sample/fast

#=============================================================================
# Target rules for targets named ysfontrenderer

# Build rule for target.
ysfontrenderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysfontrenderer
.PHONY : ysfontrenderer

# fast build rule for target.
ysfontrenderer/fast:
	$(MAKE) $(MAKESILENT) -f public/ysfontrenderer/src/CMakeFiles/ysfontrenderer.dir/build.make public/ysfontrenderer/src/CMakeFiles/ysfontrenderer.dir/build
.PHONY : ysfontrenderer/fast

#=============================================================================
# Target rules for targets named ystexturemanager

# Build rule for target.
ystexturemanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ystexturemanager
.PHONY : ystexturemanager

# fast build rule for target.
ystexturemanager/fast:
	$(MAKE) $(MAKESILENT) -f public/ystexturemanager/src/CMakeFiles/ystexturemanager.dir/build.make public/ystexturemanager/src/CMakeFiles/ystexturemanager.dir/build
.PHONY : ystexturemanager/fast

#=============================================================================
# Target rules for targets named ystexturemanager_gl

# Build rule for target.
ystexturemanager_gl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ystexturemanager_gl
.PHONY : ystexturemanager_gl

# fast build rule for target.
ystexturemanager_gl/fast:
	$(MAKE) $(MAKESILENT) -f public/ystexturemanager/src/gl/CMakeFiles/ystexturemanager_gl.dir/build.make public/ystexturemanager/src/gl/CMakeFiles/ystexturemanager_gl.dir/build
.PHONY : ystexturemanager_gl/fast

#=============================================================================
# Target rules for targets named ystexturemanager_nownd

# Build rule for target.
ystexturemanager_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ystexturemanager_nownd
.PHONY : ystexturemanager_nownd

# fast build rule for target.
ystexturemanager_nownd/fast:
	$(MAKE) $(MAKESILENT) -f public/ystexturemanager/src/null/CMakeFiles/ystexturemanager_nownd.dir/build.make public/ystexturemanager/src/null/CMakeFiles/ystexturemanager_nownd.dir/build
.PHONY : ystexturemanager_nownd/fast

#=============================================================================
# Target rules for targets named fsguilib

# Build rule for target.
fsguilib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib
.PHONY : fsguilib

# fast build rule for target.
fsguilib/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/src/CMakeFiles/fsguilib.dir/build.make public/fsguilib/src/CMakeFiles/fsguilib.dir/build
.PHONY : fsguilib/fast

#=============================================================================
# Target rules for targets named fsguilib_gl2

# Build rule for target.
fsguilib_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib_gl2
.PHONY : fsguilib_gl2

# fast build rule for target.
fsguilib_gl2/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/src/gl2/CMakeFiles/fsguilib_gl2.dir/build.make public/fsguilib/src/gl2/CMakeFiles/fsguilib_gl2.dir/build
.PHONY : fsguilib_gl2/fast

#=============================================================================
# Target rules for targets named fsguilib_gl1

# Build rule for target.
fsguilib_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib_gl1
.PHONY : fsguilib_gl1

# fast build rule for target.
fsguilib_gl1/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/src/gl1/CMakeFiles/fsguilib_gl1.dir/build.make public/fsguilib/src/gl1/CMakeFiles/fsguilib_gl1.dir/build
.PHONY : fsguilib_gl1/fast

#=============================================================================
# Target rules for targets named fsguilib_nownd

# Build rule for target.
fsguilib_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib_nownd
.PHONY : fsguilib_nownd

# fast build rule for target.
fsguilib_nownd/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/src/nownd/CMakeFiles/fsguilib_nownd.dir/build.make public/fsguilib/src/nownd/CMakeFiles/fsguilib_nownd.dir/build
.PHONY : fsguilib_nownd/fast

#=============================================================================
# Target rules for targets named fsguifiledialog

# Build rule for target.
fsguifiledialog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguifiledialog
.PHONY : fsguifiledialog

# fast build rule for target.
fsguifiledialog/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/filedialog/CMakeFiles/fsguifiledialog.dir/build.make public/fsguilib/filedialog/CMakeFiles/fsguifiledialog.dir/build
.PHONY : fsguifiledialog/fast

#=============================================================================
# Target rules for targets named fsguilib_template

# Build rule for target.
fsguilib_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib_template
.PHONY : fsguilib_template

# fast build rule for target.
fsguilib_template/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/template/CMakeFiles/fsguilib_template.dir/build.make public/fsguilib/template/CMakeFiles/fsguilib_template.dir/build
.PHONY : fsguilib_template/fast

#=============================================================================
# Target rules for targets named fsguilib_template_with_filedialog

# Build rule for target.
fsguilib_template_with_filedialog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsguilib_template_with_filedialog
.PHONY : fsguilib_template_with_filedialog

# fast build rule for target.
fsguilib_template_with_filedialog/fast:
	$(MAKE) $(MAKESILENT) -f public/fsguilib/template_with_filedialog/CMakeFiles/fsguilib_template_with_filedialog.dir/build.make public/fsguilib/template_with_filedialog/CMakeFiles/fsguilib_template_with_filedialog.dir/build
.PHONY : fsguilib_template_with_filedialog/fast

#=============================================================================
# Target rules for targets named fsgui3d

# Build rule for target.
fsgui3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d
.PHONY : fsgui3d

# fast build rule for target.
fsgui3d/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/src/CMakeFiles/fsgui3d.dir/build.make public/fsgui3d/src/CMakeFiles/fsgui3d.dir/build
.PHONY : fsgui3d/fast

#=============================================================================
# Target rules for targets named fsgui3d_gl1

# Build rule for target.
fsgui3d_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d_gl1
.PHONY : fsgui3d_gl1

# fast build rule for target.
fsgui3d_gl1/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/src/gl1/CMakeFiles/fsgui3d_gl1.dir/build.make public/fsgui3d/src/gl1/CMakeFiles/fsgui3d_gl1.dir/build
.PHONY : fsgui3d_gl1/fast

#=============================================================================
# Target rules for targets named fsgui3d_gl2

# Build rule for target.
fsgui3d_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d_gl2
.PHONY : fsgui3d_gl2

# fast build rule for target.
fsgui3d_gl2/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/src/gl2/CMakeFiles/fsgui3d_gl2.dir/build.make public/fsgui3d/src/gl2/CMakeFiles/fsgui3d_gl2.dir/build
.PHONY : fsgui3d_gl2/fast

#=============================================================================
# Target rules for targets named fsgui3d_template

# Build rule for target.
fsgui3d_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d_template
.PHONY : fsgui3d_template

# fast build rule for target.
fsgui3d_template/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/template/CMakeFiles/fsgui3d_template.dir/build.make public/fsgui3d/template/CMakeFiles/fsgui3d_template.dir/build
.PHONY : fsgui3d_template/fast

#=============================================================================
# Target rules for targets named fsgui3d_template_with_filedialog

# Build rule for target.
fsgui3d_template_with_filedialog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d_template_with_filedialog
.PHONY : fsgui3d_template_with_filedialog

# fast build rule for target.
fsgui3d_template_with_filedialog/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/template_with_filedialog/CMakeFiles/fsgui3d_template_with_filedialog.dir/build.make public/fsgui3d/template_with_filedialog/CMakeFiles/fsgui3d_template_with_filedialog.dir/build
.PHONY : fsgui3d_template_with_filedialog/fast

#=============================================================================
# Target rules for targets named fsgui3d_template_easy

# Build rule for target.
fsgui3d_template_easy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsgui3d_template_easy
.PHONY : fsgui3d_template_easy

# fast build rule for target.
fsgui3d_template_easy/fast:
	$(MAKE) $(MAKESILENT) -f public/fsgui3d/template-easy/CMakeFiles/fsgui3d_template_easy.dir/build.make public/fsgui3d/template-easy/CMakeFiles/fsgui3d_template_easy.dir/build
.PHONY : fsgui3d_template_easy/fast

#=============================================================================
# Target rules for targets named yssocket

# Build rule for target.
yssocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yssocket
.PHONY : yssocket

# fast build rule for target.
yssocket/fast:
	$(MAKE) $(MAKESILENT) -f public/yssocket/src/CMakeFiles/yssocket.dir/build.make public/yssocket/src/CMakeFiles/yssocket.dir/build
.PHONY : yssocket/fast

#=============================================================================
# Target rules for targets named geblkernel

# Build rule for target.
geblkernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblkernel
.PHONY : geblkernel

# fast build rule for target.
geblkernel/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/kernel/CMakeFiles/geblkernel.dir/build.make public/ysgebl/src/kernel/CMakeFiles/geblkernel.dir/build
.PHONY : geblkernel/fast

#=============================================================================
# Target rules for targets named geblutil

# Build rule for target.
geblutil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblutil
.PHONY : geblutil

# fast build rule for target.
geblutil/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/kernelutil/CMakeFiles/geblutil.dir/build.make public/ysgebl/src/kernelutil/CMakeFiles/geblutil.dir/build
.PHONY : geblutil/fast

#=============================================================================
# Target rules for targets named geblgl

# Build rule for target.
geblgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgl
.PHONY : geblgl

# fast build rule for target.
geblgl/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/shellrender/CMakeFiles/geblgl.dir/build.make public/ysgebl/src/shellrender/CMakeFiles/geblgl.dir/build
.PHONY : geblgl/fast

#=============================================================================
# Target rules for targets named geblgl_gl2

# Build rule for target.
geblgl_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgl_gl2
.PHONY : geblgl_gl2

# fast build rule for target.
geblgl_gl2/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/shellrender/gl2/CMakeFiles/geblgl_gl2.dir/build.make public/ysgebl/src/shellrender/gl2/CMakeFiles/geblgl_gl2.dir/build
.PHONY : geblgl_gl2/fast

#=============================================================================
# Target rules for targets named geblgl_gl1

# Build rule for target.
geblgl_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgl_gl1
.PHONY : geblgl_gl1

# fast build rule for target.
geblgl_gl1/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/shellrender/gl1/CMakeFiles/geblgl_gl1.dir/build.make public/ysgebl/src/shellrender/gl1/CMakeFiles/geblgl_gl1.dir/build
.PHONY : geblgl_gl1/fast

#=============================================================================
# Target rules for targets named geblgl_nownd

# Build rule for target.
geblgl_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgl_nownd
.PHONY : geblgl_nownd

# fast build rule for target.
geblgl_nownd/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/shellrender/nownd/CMakeFiles/geblgl_nownd.dir/build.make public/ysgebl/src/shellrender/nownd/CMakeFiles/geblgl_nownd.dir/build
.PHONY : geblgl_nownd/fast

#=============================================================================
# Target rules for targets named geblgui_foundation

# Build rule for target.
geblgui_foundation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgui_foundation
.PHONY : geblgui_foundation

# fast build rule for target.
geblgui_foundation/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/gui_foundation/CMakeFiles/geblgui_foundation.dir/build.make public/ysgebl/src/gui_foundation/CMakeFiles/geblgui_foundation.dir/build
.PHONY : geblgui_foundation/fast

#=============================================================================
# Target rules for targets named geblgui

# Build rule for target.
geblgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblgui
.PHONY : geblgui

# fast build rule for target.
geblgui/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/gui/CMakeFiles/geblgui.dir/build.make public/ysgebl/src/gui/CMakeFiles/geblgui.dir/build
.PHONY : geblgui/fast

#=============================================================================
# Target rules for targets named ysgebl64

# Build rule for target.
ysgebl64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysgebl64
.PHONY : ysgebl64

# fast build rule for target.
ysgebl64/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/main/CMakeFiles/ysgebl64.dir/build.make public/ysgebl/src/main/CMakeFiles/ysgebl64.dir/build
.PHONY : ysgebl64/fast

#=============================================================================
# Target rules for targets named geblcmdlib

# Build rule for target.
geblcmdlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblcmdlib
.PHONY : geblcmdlib

# fast build rule for target.
geblcmdlib/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/cmdlib/CMakeFiles/geblcmdlib.dir/build.make public/ysgebl/src/cmdlib/CMakeFiles/geblcmdlib.dir/build
.PHONY : geblcmdlib/fast

#=============================================================================
# Target rules for targets named geblcmd

# Build rule for target.
geblcmd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geblcmd
.PHONY : geblcmd

# fast build rule for target.
geblcmd/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/cmdmain/CMakeFiles/geblcmd.dir/build.make public/ysgebl/src/cmdmain/CMakeFiles/geblcmd.dir/build
.PHONY : geblcmd/fast

#=============================================================================
# Target rules for targets named ysshellext_sample

# Build rule for target.
ysshellext_sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysshellext_sample
.PHONY : ysshellext_sample

# fast build rule for target.
ysshellext_sample/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/samples/YsShellExt/CMakeFiles/ysshellext_sample.dir/build.make public/ysgebl/src/samples/YsShellExt/CMakeFiles/ysshellext_sample.dir/build
.PHONY : ysshellext_sample/fast

#=============================================================================
# Target rules for targets named nonManifoldToConstEdge

# Build rule for target.
nonManifoldToConstEdge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nonManifoldToConstEdge
.PHONY : nonManifoldToConstEdge

# fast build rule for target.
nonManifoldToConstEdge/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/samples/NonManifoldToConstEdge/CMakeFiles/nonManifoldToConstEdge.dir/build.make public/ysgebl/src/samples/NonManifoldToConstEdge/CMakeFiles/nonManifoldToConstEdge.dir/build
.PHONY : nonManifoldToConstEdge/fast

#=============================================================================
# Target rules for targets named booleanSubtraction

# Build rule for target.
booleanSubtraction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 booleanSubtraction
.PHONY : booleanSubtraction

# fast build rule for target.
booleanSubtraction/fast:
	$(MAKE) $(MAKESILENT) -f public/ysgebl/src/samples/BooleanSubtraction/CMakeFiles/booleanSubtraction.dir/build.make public/ysgebl/src/samples/BooleanSubtraction/CMakeFiles/booleanSubtraction.dir/build
.PHONY : booleanSubtraction/fast

#=============================================================================
# Target rules for targets named irsensor_gui

# Build rule for target.
irsensor_gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irsensor_gui
.PHONY : irsensor_gui

# fast build rule for target.
irsensor_gui/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/gui/CMakeFiles/irsensor_gui.dir/build.make public/ir_transceiver/gui/CMakeFiles/irsensor_gui.dir/build
.PHONY : irsensor_gui/fast

#=============================================================================
# Target rules for targets named irsend

# Build rule for target.
irsend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irsend
.PHONY : irsend

# fast build rule for target.
irsend/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/cui_transmitter/CMakeFiles/irsend.dir/build.make public/ir_transceiver/cui_transmitter/CMakeFiles/irsend.dir/build
.PHONY : irsend/fast

#=============================================================================
# Target rules for targets named cheapgui

# Build rule for target.
cheapgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cheapgui
.PHONY : cheapgui

# fast build rule for target.
cheapgui/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/cheapgui/CMakeFiles/cheapgui.dir/build.make public/ir_transceiver/lib/cheapgui/CMakeFiles/cheapgui.dir/build
.PHONY : cheapgui/fast

#=============================================================================
# Target rules for targets named cheapgui_gl1

# Build rule for target.
cheapgui_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cheapgui_gl1
.PHONY : cheapgui_gl1

# fast build rule for target.
cheapgui_gl1/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/cheapgui/CMakeFiles/cheapgui_gl1.dir/build.make public/ir_transceiver/lib/cheapgui/CMakeFiles/cheapgui_gl1.dir/build
.PHONY : cheapgui_gl1/fast

#=============================================================================
# Target rules for targets named cheapgui_template

# Build rule for target.
cheapgui_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cheapgui_template
.PHONY : cheapgui_template

# fast build rule for target.
cheapgui_template/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/cheapgui/template/CMakeFiles/cheapgui_template.dir/build.make public/ir_transceiver/lib/cheapgui/template/CMakeFiles/cheapgui_template.dir/build
.PHONY : cheapgui_template/fast

#=============================================================================
# Target rules for targets named cheaplib

# Build rule for target.
cheaplib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cheaplib
.PHONY : cheaplib

# fast build rule for target.
cheaplib/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/cheaplib/CMakeFiles/cheaplib.dir/build.make public/ir_transceiver/lib/cheaplib/CMakeFiles/cheaplib.dir/build
.PHONY : cheaplib/fast

#=============================================================================
# Target rules for targets named irtoylib

# Build rule for target.
irtoylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irtoylib
.PHONY : irtoylib

# fast build rule for target.
irtoylib/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/irtoy/CMakeFiles/irtoylib.dir/build.make public/ir_transceiver/lib/irtoy/CMakeFiles/irtoylib.dir/build
.PHONY : irtoylib/fast

#=============================================================================
# Target rules for targets named comportlib

# Build rule for target.
comportlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comportlib
.PHONY : comportlib

# fast build rule for target.
comportlib/fast:
	$(MAKE) $(MAKESILENT) -f public/ir_transceiver/lib/yscomport/CMakeFiles/comportlib.dir/build.make public/ir_transceiver/lib/yscomport/CMakeFiles/comportlib.dir/build
.PHONY : comportlib/fast

#=============================================================================
# Target rules for targets named ysflight_common

# Build rule for target.
ysflight_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_common
.PHONY : ysflight_common

# fast build rule for target.
ysflight_common/fast:
	$(MAKE) $(MAKESILENT) -f common/CMakeFiles/ysflight_common.dir/build.make common/CMakeFiles/ysflight_common.dir/build
.PHONY : ysflight_common/fast

#=============================================================================
# Target rules for targets named ysflight_config

# Build rule for target.
ysflight_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_config
.PHONY : ysflight_config

# fast build rule for target.
ysflight_config/fast:
	$(MAKE) $(MAKESILENT) -f config/CMakeFiles/ysflight_config.dir/build.make config/CMakeFiles/ysflight_config.dir/build
.PHONY : ysflight_config/fast

#=============================================================================
# Target rules for targets named ysflight_platform_common

# Build rule for target.
ysflight_platform_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_platform_common
.PHONY : ysflight_platform_common

# fast build rule for target.
ysflight_platform_common/fast:
	$(MAKE) $(MAKESILENT) -f platform/common/CMakeFiles/ysflight_platform_common.dir/build.make platform/common/CMakeFiles/ysflight_platform_common.dir/build
.PHONY : ysflight_platform_common/fast

#=============================================================================
# Target rules for targets named ysflight_filename

# Build rule for target.
ysflight_filename: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_filename
.PHONY : ysflight_filename

# fast build rule for target.
ysflight_filename/fast:
	$(MAKE) $(MAKESILENT) -f filename/CMakeFiles/ysflight_filename.dir/build.make filename/CMakeFiles/ysflight_filename.dir/build
.PHONY : ysflight_filename/fast

#=============================================================================
# Target rules for targets named ysflight_dynamics

# Build rule for target.
ysflight_dynamics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_dynamics
.PHONY : ysflight_dynamics

# fast build rule for target.
ysflight_dynamics/fast:
	$(MAKE) $(MAKESILENT) -f dynamics/CMakeFiles/ysflight_dynamics.dir/build.make dynamics/CMakeFiles/ysflight_dynamics.dir/build
.PHONY : ysflight_dynamics/fast

#=============================================================================
# Target rules for targets named ysflight_autopilot

# Build rule for target.
ysflight_autopilot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_autopilot
.PHONY : ysflight_autopilot

# fast build rule for target.
ysflight_autopilot/fast:
	$(MAKE) $(MAKESILENT) -f autopilot/CMakeFiles/ysflight_autopilot.dir/build.make autopilot/CMakeFiles/ysflight_autopilot.dir/build
.PHONY : ysflight_autopilot/fast

#=============================================================================
# Target rules for targets named ysflight_pathplanning

# Build rule for target.
ysflight_pathplanning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_pathplanning
.PHONY : ysflight_pathplanning

# fast build rule for target.
ysflight_pathplanning/fast:
	$(MAKE) $(MAKESILENT) -f pathplanning/CMakeFiles/ysflight_pathplanning.dir/build.make pathplanning/CMakeFiles/ysflight_pathplanning.dir/build
.PHONY : ysflight_pathplanning/fast

#=============================================================================
# Target rules for targets named ysflight_externalconsole

# Build rule for target.
ysflight_externalconsole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_externalconsole
.PHONY : ysflight_externalconsole

# fast build rule for target.
ysflight_externalconsole/fast:
	$(MAKE) $(MAKESILENT) -f externalconsole/CMakeFiles/ysflight_externalconsole.dir/build.make externalconsole/CMakeFiles/ysflight_externalconsole.dir/build
.PHONY : ysflight_externalconsole/fast

#=============================================================================
# Target rules for targets named ysflight_util

# Build rule for target.
ysflight_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_util
.PHONY : ysflight_util

# fast build rule for target.
ysflight_util/fast:
	$(MAKE) $(MAKESILENT) -f util/CMakeFiles/ysflight_util.dir/build.make util/CMakeFiles/ysflight_util.dir/build
.PHONY : ysflight_util/fast

#=============================================================================
# Target rules for targets named ysflight_vehicle

# Build rule for target.
ysflight_vehicle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_vehicle
.PHONY : ysflight_vehicle

# fast build rule for target.
ysflight_vehicle/fast:
	$(MAKE) $(MAKESILENT) -f vehicle/CMakeFiles/ysflight_vehicle.dir/build.make vehicle/CMakeFiles/ysflight_vehicle.dir/build
.PHONY : ysflight_vehicle/fast

#=============================================================================
# Target rules for targets named ysscenery_dnm

# Build rule for target.
ysscenery_dnm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysscenery_dnm
.PHONY : ysscenery_dnm

# fast build rule for target.
ysscenery_dnm/fast:
	$(MAKE) $(MAKESILENT) -f scenery/CMakeFiles/ysscenery_dnm.dir/build.make scenery/CMakeFiles/ysscenery_dnm.dir/build
.PHONY : ysscenery_dnm/fast

#=============================================================================
# Target rules for targets named ysscenery_dnm_gl1

# Build rule for target.
ysscenery_dnm_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysscenery_dnm_gl1
.PHONY : ysscenery_dnm_gl1

# fast build rule for target.
ysscenery_dnm_gl1/fast:
	$(MAKE) $(MAKESILENT) -f scenery/CMakeFiles/ysscenery_dnm_gl1.dir/build.make scenery/CMakeFiles/ysscenery_dnm_gl1.dir/build
.PHONY : ysscenery_dnm_gl1/fast

#=============================================================================
# Target rules for targets named ysscenery_dnm_gl2

# Build rule for target.
ysscenery_dnm_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysscenery_dnm_gl2
.PHONY : ysscenery_dnm_gl2

# fast build rule for target.
ysscenery_dnm_gl2/fast:
	$(MAKE) $(MAKESILENT) -f scenery/CMakeFiles/ysscenery_dnm_gl2.dir/build.make scenery/CMakeFiles/ysscenery_dnm_gl2.dir/build
.PHONY : ysscenery_dnm_gl2/fast

#=============================================================================
# Target rules for targets named ysscenery_dnm_nownd

# Build rule for target.
ysscenery_dnm_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysscenery_dnm_nownd
.PHONY : ysscenery_dnm_nownd

# fast build rule for target.
ysscenery_dnm_nownd/fast:
	$(MAKE) $(MAKESILENT) -f scenery/CMakeFiles/ysscenery_dnm_nownd.dir/build.make scenery/CMakeFiles/ysscenery_dnm_nownd.dir/build
.PHONY : ysscenery_dnm_nownd/fast

#=============================================================================
# Target rules for targets named ysjoystick

# Build rule for target.
ysjoystick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysjoystick
.PHONY : ysjoystick

# fast build rule for target.
ysjoystick/fast:
	$(MAKE) $(MAKESILENT) -f ysjoystick/src/CMakeFiles/ysjoystick.dir/build.make ysjoystick/src/CMakeFiles/ysjoystick.dir/build
.PHONY : ysjoystick/fast

#=============================================================================
# Target rules for targets named ysjoycalibdlg_gl1

# Build rule for target.
ysjoycalibdlg_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysjoycalibdlg_gl1
.PHONY : ysjoycalibdlg_gl1

# fast build rule for target.
ysjoycalibdlg_gl1/fast:
	$(MAKE) $(MAKESILENT) -f ysjoystick/src/CMakeFiles/ysjoycalibdlg_gl1.dir/build.make ysjoystick/src/CMakeFiles/ysjoycalibdlg_gl1.dir/build
.PHONY : ysjoycalibdlg_gl1/fast

#=============================================================================
# Target rules for targets named ysjoycalibdlg_gl2

# Build rule for target.
ysjoycalibdlg_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysjoycalibdlg_gl2
.PHONY : ysjoycalibdlg_gl2

# fast build rule for target.
ysjoycalibdlg_gl2/fast:
	$(MAKE) $(MAKESILENT) -f ysjoystick/src/CMakeFiles/ysjoycalibdlg_gl2.dir/build.make ysjoystick/src/CMakeFiles/ysjoycalibdlg_gl2.dir/build
.PHONY : ysjoycalibdlg_gl2/fast

#=============================================================================
# Target rules for targets named ysflight_graphics_common

# Build rule for target.
ysflight_graphics_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_graphics_common
.PHONY : ysflight_graphics_common

# fast build rule for target.
ysflight_graphics_common/fast:
	$(MAKE) $(MAKESILENT) -f graphics/common/CMakeFiles/ysflight_graphics_common.dir/build.make graphics/common/CMakeFiles/ysflight_graphics_common.dir/build
.PHONY : ysflight_graphics_common/fast

#=============================================================================
# Target rules for targets named ysflight_graphics_gl1

# Build rule for target.
ysflight_graphics_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_graphics_gl1
.PHONY : ysflight_graphics_gl1

# fast build rule for target.
ysflight_graphics_gl1/fast:
	$(MAKE) $(MAKESILENT) -f graphics/gl/CMakeFiles/ysflight_graphics_gl1.dir/build.make graphics/gl/CMakeFiles/ysflight_graphics_gl1.dir/build
.PHONY : ysflight_graphics_gl1/fast

#=============================================================================
# Target rules for targets named ysflight_graphics_gl2

# Build rule for target.
ysflight_graphics_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_graphics_gl2
.PHONY : ysflight_graphics_gl2

# fast build rule for target.
ysflight_graphics_gl2/fast:
	$(MAKE) $(MAKESILENT) -f graphics/gl2.0/CMakeFiles/ysflight_graphics_gl2.dir/build.make graphics/gl2.0/CMakeFiles/ysflight_graphics_gl2.dir/build
.PHONY : ysflight_graphics_gl2/fast

#=============================================================================
# Target rules for targets named ysflight_graphics_null

# Build rule for target.
ysflight_graphics_null: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_graphics_null
.PHONY : ysflight_graphics_null

# fast build rule for target.
ysflight_graphics_null/fast:
	$(MAKE) $(MAKESILENT) -f graphics/null/CMakeFiles/ysflight_graphics_null.dir/build.make graphics/null/CMakeFiles/ysflight_graphics_null.dir/build
.PHONY : ysflight_graphics_null/fast

#=============================================================================
# Target rules for targets named ysflight_platform_linux

# Build rule for target.
ysflight_platform_linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_platform_linux
.PHONY : ysflight_platform_linux

# fast build rule for target.
ysflight_platform_linux/fast:
	$(MAKE) $(MAKESILENT) -f platform/linux/CMakeFiles/ysflight_platform_linux.dir/build.make platform/linux/CMakeFiles/ysflight_platform_linux.dir/build
.PHONY : ysflight_platform_linux/fast

#=============================================================================
# Target rules for targets named sndYsflight64

# Build rule for target.
sndYsflight64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sndYsflight64
.PHONY : sndYsflight64

# fast build rule for target.
sndYsflight64/fast:
	$(MAKE) $(MAKESILENT) -f sounddll/linux-alsa/CMakeFiles/sndYsflight64.dir/build.make sounddll/linux-alsa/CMakeFiles/sndYsflight64.dir/build
.PHONY : sndYsflight64/fast

#=============================================================================
# Target rules for targets named sndYsflight64-pulse

# Build rule for target.
sndYsflight64-pulse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sndYsflight64-pulse
.PHONY : sndYsflight64-pulse

# fast build rule for target.
sndYsflight64-pulse/fast:
	$(MAKE) $(MAKESILENT) -f sounddll/linux-pulseaudio/CMakeFiles/sndYsflight64-pulse.dir/build.make sounddll/linux-pulseaudio/CMakeFiles/sndYsflight64-pulse.dir/build
.PHONY : sndYsflight64-pulse/fast

#=============================================================================
# Target rules for targets named voiceYsflight64

# Build rule for target.
voiceYsflight64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voiceYsflight64
.PHONY : voiceYsflight64

# fast build rule for target.
voiceYsflight64/fast:
	$(MAKE) $(MAKESILENT) -f voicedll/generic/CMakeFiles/voiceYsflight64.dir/build.make voicedll/generic/CMakeFiles/voiceYsflight64.dir/build
.PHONY : voiceYsflight64/fast

#=============================================================================
# Target rules for targets named ysflight_platform_nownd

# Build rule for target.
ysflight_platform_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_platform_nownd
.PHONY : ysflight_platform_nownd

# fast build rule for target.
ysflight_platform_nownd/fast:
	$(MAKE) $(MAKESILENT) -f platform/nownd/CMakeFiles/ysflight_platform_nownd.dir/build.make platform/nownd/CMakeFiles/ysflight_platform_nownd.dir/build
.PHONY : ysflight_platform_nownd/fast

#=============================================================================
# Target rules for targets named ysflight_core

# Build rule for target.
ysflight_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_core
.PHONY : ysflight_core

# fast build rule for target.
ysflight_core/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/ysflight_core.dir/build.make core/CMakeFiles/ysflight_core.dir/build
.PHONY : ysflight_core/fast

#=============================================================================
# Target rules for targets named ysflight_ui

# Build rule for target.
ysflight_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_ui
.PHONY : ysflight_ui

# fast build rule for target.
ysflight_ui/fast:
	$(MAKE) $(MAKESILENT) -f ui/CMakeFiles/ysflight_ui.dir/build.make ui/CMakeFiles/ysflight_ui.dir/build
.PHONY : ysflight_ui/fast

#=============================================================================
# Target rules for targets named ysflight_gui

# Build rule for target.
ysflight_gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight_gui
.PHONY : ysflight_gui

# fast build rule for target.
ysflight_gui/fast:
	$(MAKE) $(MAKESILENT) -f gui/CMakeFiles/ysflight_gui.dir/build.make gui/CMakeFiles/ysflight_gui.dir/build
.PHONY : ysflight_gui/fast

#=============================================================================
# Target rules for targets named ysflight64_gl2

# Build rule for target.
ysflight64_gl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight64_gl2
.PHONY : ysflight64_gl2

# fast build rule for target.
ysflight64_gl2/fast:
	$(MAKE) $(MAKESILENT) -f main/CMakeFiles/ysflight64_gl2.dir/build.make main/CMakeFiles/ysflight64_gl2.dir/build
.PHONY : ysflight64_gl2/fast

#=============================================================================
# Target rules for targets named ysflight64_gl1

# Build rule for target.
ysflight64_gl1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight64_gl1
.PHONY : ysflight64_gl1

# fast build rule for target.
ysflight64_gl1/fast:
	$(MAKE) $(MAKESILENT) -f main/CMakeFiles/ysflight64_gl1.dir/build.make main/CMakeFiles/ysflight64_gl1.dir/build
.PHONY : ysflight64_gl1/fast

#=============================================================================
# Target rules for targets named ysflight64_nownd

# Build rule for target.
ysflight64_nownd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight64_nownd
.PHONY : ysflight64_nownd

# fast build rule for target.
ysflight64_nownd/fast:
	$(MAKE) $(MAKESILENT) -f main_consvr/CMakeFiles/ysflight64_nownd.dir/build.make main_consvr/CMakeFiles/ysflight64_nownd.dir/build
.PHONY : ysflight64_nownd/fast

#=============================================================================
# Target rules for targets named ysflight64_gl2demo

# Build rule for target.
ysflight64_gl2demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight64_gl2demo
.PHONY : ysflight64_gl2demo

# fast build rule for target.
ysflight64_gl2demo/fast:
	$(MAKE) $(MAKESILENT) -f main_demoOnly/CMakeFiles/ysflight64_gl2demo.dir/build.make main_demoOnly/CMakeFiles/ysflight64_gl2demo.dir/build
.PHONY : ysflight64_gl2demo/fast

#=============================================================================
# Target rules for targets named ysflight64_gl1demo

# Build rule for target.
ysflight64_gl1demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ysflight64_gl1demo
.PHONY : ysflight64_gl1demo

# fast build rule for target.
ysflight64_gl1demo/fast:
	$(MAKE) $(MAKESILENT) -f main_demoOnly/CMakeFiles/ysflight64_gl1demo.dir/build.make main_demoOnly/CMakeFiles/ysflight64_gl1demo.dir/build
.PHONY : ysflight64_gl1demo/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ysglsl_expand_source"
	@echo "... ysglslprogram_c"
	@echo "... ysglslprogram_h"
	@echo "... booleanSubtraction"
	@echo "... cheapgui"
	@echo "... cheapgui_gl1"
	@echo "... cheapgui_template"
	@echo "... cheaplib"
	@echo "... comportlib"
	@echo "... fsgui3d"
	@echo "... fsgui3d_gl1"
	@echo "... fsgui3d_gl2"
	@echo "... fsgui3d_template"
	@echo "... fsgui3d_template_easy"
	@echo "... fsgui3d_template_with_filedialog"
	@echo "... fsguifiledialog"
	@echo "... fsguilib"
	@echo "... fsguilib_gl1"
	@echo "... fsguilib_gl2"
	@echo "... fsguilib_nownd"
	@echo "... fsguilib_template"
	@echo "... fsguilib_template_with_filedialog"
	@echo "... fslazywindow"
	@echo "... fslazywindow_template"
	@echo "... fssimplefiledialog"
	@echo "... fssimplefiledialog_sample"
	@echo "... fssimplenowindow"
	@echo "... fssimplewindow"
	@echo "... fssimplewindow_template"
	@echo "... geblcmd"
	@echo "... geblcmdlib"
	@echo "... geblgl"
	@echo "... geblgl_gl1"
	@echo "... geblgl_gl2"
	@echo "... geblgl_nownd"
	@echo "... geblgui"
	@echo "... geblgui_foundation"
	@echo "... geblkernel"
	@echo "... geblutil"
	@echo "... irsend"
	@echo "... irsensor_gui"
	@echo "... irtoylib"
	@echo "... nonManifoldToConstEdge"
	@echo "... playwav"
	@echo "... sample00-lineart"
	@echo "... sample00_bouncingBall"
	@echo "... sample01-squash"
	@echo "... sample02-echo"
	@echo "... sample03-mouse"
	@echo "... sample04-cube"
	@echo "... sample05-key"
	@echo "... sample06-15puzzle"
	@echo "... sndYsflight64"
	@echo "... sndYsflight64-pulse"
	@echo "... test_fullscreen"
	@echo "... test_resize"
	@echo "... voiceYsflight64"
	@echo "... ys_bitmap_command_base"
	@echo "... ysbitmap"
	@echo "... ysbitmapfont"
	@echo "... ysbitmaputil"
	@echo "... ysclass"
	@echo "... ysclass11"
	@echo "... yscropbmp"
	@echo "... ysflight64_gl1"
	@echo "... ysflight64_gl1demo"
	@echo "... ysflight64_gl2"
	@echo "... ysflight64_gl2demo"
	@echo "... ysflight64_nownd"
	@echo "... ysflight_autopilot"
	@echo "... ysflight_common"
	@echo "... ysflight_config"
	@echo "... ysflight_core"
	@echo "... ysflight_dynamics"
	@echo "... ysflight_externalconsole"
	@echo "... ysflight_filename"
	@echo "... ysflight_graphics_common"
	@echo "... ysflight_graphics_gl1"
	@echo "... ysflight_graphics_gl2"
	@echo "... ysflight_graphics_null"
	@echo "... ysflight_gui"
	@echo "... ysflight_pathplanning"
	@echo "... ysflight_platform_common"
	@echo "... ysflight_platform_linux"
	@echo "... ysflight_platform_nownd"
	@echo "... ysflight_ui"
	@echo "... ysflight_util"
	@echo "... ysflight_vehicle"
	@echo "... ysfontrenderer"
	@echo "... ysgebl64"
	@echo "... ysgl"
	@echo "... ysgl_makec"
	@echo "... ysgl_makeh"
	@echo "... ysgl_preproc"
	@echo "... ysglcpp"
	@echo "... ysglcpp_gl1"
	@echo "... ysglcpp_gl2"
	@echo "... ysglcpp_nownd"
	@echo "... ysinvertbmp"
	@echo "... ysjoycalibdlg_gl1"
	@echo "... ysjoycalibdlg_gl2"
	@echo "... ysjoystick"
	@echo "... ysmakealphamask"
	@echo "... ysmakeblackwhite"
	@echo "... ysmakeblankbmp"
	@echo "... ysmakebmptile"
	@echo "... ysmakedensitymap"
	@echo "... ysmaketextbmp"
	@echo "... ysmakewhitetransparent"
	@echo "... ysnegatebmp"
	@echo "... ysnullsystemfont"
	@echo "... yspastebmp"
	@echo "... ysport"
	@echo "... ysresizebmp"
	@echo "... ysscenery_dnm"
	@echo "... ysscenery_dnm_gl1"
	@echo "... ysscenery_dnm_gl2"
	@echo "... ysscenery_dnm_nownd"
	@echo "... ysshellext_sample"
	@echo "... yssimplesound"
	@echo "... yssimplesound_linux_alsa"
	@echo "... yssimplesound_nownd"
	@echo "... yssimplesound_sample"
	@echo "... yssimplesound_sample_fssimplewindow"
	@echo "... yssimplesound_streamtest"
	@echo "... yssimplesound_stressTest"
	@echo "... yssimplesound_test"
	@echo "... yssimplesound_test01"
	@echo "... yssocket"
	@echo "... yssystemfont"
	@echo "... ystexturemanager"
	@echo "... ystexturemanager_gl"
	@echo "... ystexturemanager_nownd"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

