name: Continuous Integration

on:
  push:
    branches: [ master ]
    tags-ignore:
      - 'v*' # Don't run if tagged as v*.
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout_public
      run: git clone https://github.com/captainys/public.git
    - name: mkdir
      run: mkdir ci_windows
    - name: cmake
      run: cmake ../src
      working-directory: ./ci_windows
    - name: build
      run: cmake --build . --config Release --parallel --target ysflight64_gl1 ysflight64_gl2 ysflight64_gl1demo ysflight64_gl2demo ysflight64_nownd
      # Cannot build ysflight64_d3d9 in github workflow because the virtual machine does not have DirectX9 libraries.
      working-directory: ./ci_windows



  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout_public
      run: git clone https://github.com/captainys/public.git
    - name: mkdir
      run: mkdir ci_ubuntu
    - name: apt-get-update
      run: sudo apt-get update
    - name: install-OpenGL
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev
    - name: install-ALSA
      run: sudo apt-get install libasound2 libasound2-dev
    - name: install-PulseAudio
      run: sudo apt-get install pulseaudio libpulse-dev
    - name: install-Python
      run: sudo apt-get install python3 python-is-python3
    - name: cmake
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release
      working-directory: ./ci_ubuntu
    - name: build
      run: cmake --build . --config Release --parallel --target ysflight64_gl1 ysflight64_gl2 ysflight64_gl1demo ysflight64_gl2demo ysflight64_nownd
      working-directory: ./ci_ubuntu



  build-macos:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: checkout_public
      run: git clone https://github.com/captainys/public.git
    - name: mkdir
      run: mkdir ci_macos
    - name: cmake
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release
      working-directory: ./ci_macos
    - name: build
      run: cmake --build . --config Release --parallel --target ysflight64_gl1 ysflight64_gl2 ysflight64_gl1demo ysflight64_gl2demo ysflight64_nownd
      working-directory: ./ci_macos
